sofastack/sofa-boot

.travis.yml
README.md
healthcheck-sofa-boot-starter/pom.xml
how-to-contribute.md
infra-sofa-boot-starter/pom.xml
runtime-sofa-boot-starter/pom.xml
sofaboot-dependencies/pom.xml
sofaboot-samples/pom.xml
sofaboot-samples/sofaboot-sample-with-isolation/pom.xml

How to contribute to SOFA Boot Doc Updated

How to contribute to SOFA Boot

---

README.md

Update readme docs and configs

---

healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/configuration/HealthCheckConfigurationMapping.java
healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/core/HealthCheckManager.java
healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/service/SofaBootComponentHealthCheckInfo.java
healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/service/SpringContextStartUpHealthCheckStatusCheckInfo.java
healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/startup/StartUpHealthCheckStatus.java
healthcheck-sofa-boot-starter/src/test/java/com/alipay/sofa/healthcheck/core/ComponentCheckProcessorTest.java
infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/constants/SystemPropertyConstants.java
infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/endpoint/SofaBootVersionEndpoint.java
infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/bean/SofaBootVersionImpl.java
infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/bean/SofaRestVersionImpl.java
infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/bean/SofaRpcVersionImpl.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/SofaFrameworkImpl.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/api/client/param/ServiceParam.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/client/impl/ClientFactoryImpl.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/component/impl/ComponentManagerImpl.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/initializer/SofaFrameworkInitializer.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/service/component/AbstractContract.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/service/component/ReferenceComponent.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/service/component/ServiceComponent.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/factory/AbstractContractFactoryBean.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/parser/AbstractContractDefinitionParser.java

Update Code Style

---

runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/api/component/AppConfiguration.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/impl/AppConfigurationImpl.java

remove useless interface

---

sofaboot-dependencies/pom.xml

+ move javadoc plugin
+ add rpc-sofa-boot-starter ark plugin dependency
+ update SOFAArk Version to 0.2.0

Update sofa ark version

---

healthcheck-sofa-boot-starter/pom.xml
healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/service/EndPointConfig.java
healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/service/SofaBootReadinessCheckEndpoint.java
healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/service/SofaBootReadinessCheckMvcEndpoint.java
healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/startup/HealthCheckTrigger.java
healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/startup/ReadinessCheckProcessor.java
healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/startup/StartUpHealthCheckStatus.java
healthcheck-sofa-boot-starter/src/test/java/com/alipay/sofa/healthcheck/readiness/DownHealthIndicataor.java
healthcheck-sofa-boot-starter/src/test/java/com/alipay/sofa/healthcheck/readiness/ReadinessCheckHttpCodeTest.java
healthcheck-sofa-boot-starter/src/test/java/com/alipay/sofa/healthcheck/readiness/ReadinessCheckProcessorTest.java
infra-sofa-boot-starter/pom.xml
infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/log/AllInfraLoggerFactoryTest.java
pom.xml
runtime-sofa-boot-starter/pom.xml
sofaboot-dependencies/pom.xml
test-sofa-boot-starter/pom.xml

Add a MvcEndPoint to add a status code mapping
Fix issue #27

Fix readiness check http status code bug

---

appveyor.yml

add windows ci script

---

infra-sofa-boot-starter/src/main/resources/META-INF/com/alipay/sofa/infra/config/spring/namespace/schema/rpc.xsd

1.add  registry config 
2. remove unused filter

add registry config

---

infra-sofa-boot-starter/src/main/resources/META-INF/com/alipay/sofa/infra/config/spring/namespace/schema/rpc.xsd

only add xsd for  bolt 
dubbo and rest don't support  custom serialization

add serialize type to bolt

---

infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/initializer/SOFABootInfrastructureSpringContextInitializer.java
sofaboot-dependencies/pom.xml

Tracer and Lookout governance;package renamed in sofa-common-tools

Tracer and Lookout governance

---

sofaboot-dependencies/pom.xml

* add lookout client modules in the sofaboot-dependencies  
* upgrade version to 1.4.1

#84 add lookout client modules in the sofaboot-dependencies pom

---

sofaboot-dependencies/pom.xml

support snapshot

---

sofaboot-dependencies/pom.xml

update rpc version to 5.4.2

---

healthcheck-sofa-boot-starter/pom.xml
infra-sofa-boot-starter/pom.xml
isle-sofa-boot-starter/pom.xml
pom.xml
runtime-sofa-boot-starter/pom.xml
sofaboot-dependencies/pom.xml
sofaboot-samples/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/service-consumer/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/service-facade/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/service-provider/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/sofa-boot-run/pom.xml
sofaboot-samples/sofaboot-sample-with-isolation/pom.xml
sofaboot-samples/sofaboot-sample-with-rpc/pom.xml
sofaboot-samples/sofaboot-sample/pom.xml
test-sofa-boot-starter/pom.xml

upgrade version 2.4.2

---

sofaboot-dependencies/pom.xml

feat: change rpc starter to 5.4.3

---

healthcheck-sofa-boot-starter/pom.xml
infra-sofa-boot-starter/pom.xml
isle-sofa-boot-starter/pom.xml
pom.xml
runtime-sofa-boot-starter/pom.xml
sofaboot-dependencies/pom.xml
sofaboot-samples/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/README.md
sofaboot-samples/sofaboot-sample-with-isle/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/service-consumer/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/service-facade/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/service-provider/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/sofa-boot-run/pom.xml
sofaboot-samples/sofaboot-sample-with-isolation/pom.xml
sofaboot-samples/sofaboot-sample-with-rpc/README.md
sofaboot-samples/sofaboot-sample-with-rpc/pom.xml
sofaboot-samples/sofaboot-sample/pom.xml
test-sofa-boot-starter/pom.xml

change sofa boot version to 2.4.3

---

sofaboot-dependencies/pom.xml

upgrade ark & jarslink version

---

README.md
infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/constants/CommonMiddlewareConstants.java
infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/env/EnvironmentCustomizer.java
infra-sofa-boot-starter/src/main/resources/META-INF/spring.factories
infra-sofa-boot-starter/src/main/resources/banner.txt
runtime-sofa-boot-starter/pom.xml

Add sofa boot version info to banner.

---

healthcheck-sofa-boot-starter/pom.xml
healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/initializer/HealthCheckInitializer.java
healthcheck-sofa-boot-starter/src/main/resources/META-INF/spring.factories
runtime-sofa-boot-starter/pom.xml
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spi/log/SofaRuntimeLoggerFactory.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/initializer/SofaRuntimeSpringContextInitializer.java
runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/ark/SofaEventHandlerTest.java
runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/log/SofaRuntimeLoggerFactoryTest.java

Unified using SofaBootLogSpaceIsolationInit.

---

.gitignore

增加mac soucetree下忽略~/.m2文件夹!
PS:第一次在github上尝试为开源项目提PR（虽然只是简单的修改，但也希望尝试不断地为开源社区去做点贡献吧），在此之前是已经提了一次这个小改动的但是是说有CLA签名问题，在网上搜索了一圈应该是本地git提交的是用户名和邮箱没有对上，先重新改动尝试一下再次提个PR（虽说也仅仅只是个一个个非常非常小几乎可以忽略不计的提交，但既然之前已经提了那现在就还是继续争取做好这个吧！后续自己会继续努力阅读源码和跟进项目，尝试提交一下真正的代码功能，谢谢！）

ignore git ~/.m2 for mac sourceTree

---

infra-sofa-boot-starter/src/main/resources/META-INF/com/alipay/sofa/infra/config/spring/namespace/schema/rpc.xsd

add generic-invoke translate to dubbo xsd

support dubbo convert

---

healthcheck-sofa-boot-starter/pom.xml
infra-sofa-boot-starter/pom.xml
isle-sofa-boot-starter/pom.xml
pom.xml
runtime-sofa-boot-plugin/pom.xml
runtime-sofa-boot-starter/pom.xml
sofaboot-dependencies/pom.xml
sofaboot-samples/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/README.md
sofaboot-samples/sofaboot-sample-with-isle/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/service-consumer/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/service-facade/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/service-provider/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/sofa-boot-run/pom.xml
sofaboot-samples/sofaboot-sample-with-isolation/pom.xml
sofaboot-samples/sofaboot-sample-with-rpc/README.md
sofaboot-samples/sofaboot-sample-with-rpc/pom.xml
sofaboot-samples/sofaboot-sample/pom.xml
test-sofa-boot-starter/pom.xml

Prepare to release.

---

healthcheck-sofa-boot-starter/pom.xml
infra-sofa-boot-starter/pom.xml
isle-sofa-boot-starter/pom.xml
pom.xml
runtime-sofa-boot-plugin/pom.xml
runtime-sofa-boot-starter/pom.xml
sofaboot-dependencies/pom.xml
sofaboot-samples/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/service-consumer/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/service-facade/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/service-provider/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/sofa-boot-run/pom.xml
sofaboot-samples/sofaboot-sample-with-isolation/pom.xml
sofaboot-samples/sofaboot-sample-with-rpc/pom.xml
sofaboot-samples/sofaboot-sample/pom.xml
test-sofa-boot-starter/pom.xml

change boot version 2.4.6-SNAPSHOT
change rpc version to 5.4.5-SNAPSHOT

Change version 246

---

healthcheck-sofa-boot-starter/pom.xml
infra-sofa-boot-starter/pom.xml
isle-sofa-boot-starter/pom.xml
pom.xml
runtime-sofa-boot-plugin/pom.xml
runtime-sofa-boot-starter/pom.xml
sofaboot-dependencies/pom.xml
sofaboot-samples/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/README.md
sofaboot-samples/sofaboot-sample-with-isle/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/service-consumer/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/service-facade/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/service-provider/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/sofa-boot-run/pom.xml
sofaboot-samples/sofaboot-sample-with-isolation/pom.xml
sofaboot-samples/sofaboot-sample-with-rpc/README.md
sofaboot-samples/sofaboot-sample-with-rpc/pom.xml
sofaboot-samples/sofaboot-sample/pom.xml
test-sofa-boot-starter/pom.xml

Upgrade version 2.4.6

---

healthcheck-sofa-boot-starter/pom.xml
infra-sofa-boot-starter/pom.xml
isle-sofa-boot-starter/pom.xml
pom.xml
runtime-sofa-boot-plugin/pom.xml
runtime-sofa-boot-starter/pom.xml
sofaboot-dependencies/pom.xml
sofaboot-samples/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/README.md
sofaboot-samples/sofaboot-sample-with-isle/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/service-consumer/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/service-facade/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/service-provider/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/sofa-boot-run/pom.xml
sofaboot-samples/sofaboot-sample-with-isolation/pom.xml
sofaboot-samples/sofaboot-sample-with-rpc/README.md
sofaboot-samples/sofaboot-sample-with-rpc/pom.xml
sofaboot-samples/sofaboot-sample/pom.xml
test-sofa-boot-starter/pom.xml

Degrade bolt version.

---

runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/component/impl/ComponentManagerImpl.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spi/component/AbstractComponent.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spi/component/ComponentInfo.java
runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/component/impl/ComponentManagerImplTest.java

Support whether component can be duplicated registered

---

sofaboot-samples/sofaboot-sample-standard/README.md
sofaboot-samples/sofaboot-sample-standard/app/biz/service-impl/pom.xml
sofaboot-samples/sofaboot-sample-standard/app/biz/service-impl/src/main/java/com/alipay/sofa/service/impl/NewWriteServiceImpl.java
sofaboot-samples/sofaboot-sample-standard/app/biz/service-impl/src/main/resources/META-INF/spring/biz-service-impl.xml
sofaboot-samples/sofaboot-sample-standard/app/biz/service-impl/src/main/resources/sofa-module.properties
sofaboot-samples/sofaboot-sample-standard/app/biz/shared/pom.xml
sofaboot-samples/sofaboot-sample-standard/app/biz/shared/src/main/java/com/alipay/sofa/service/shared/NewReadServiceImpl.java
sofaboot-samples/sofaboot-sample-standard/app/biz/shared/src/main/resources/META-INF/spring/biz-shared-service.xml
sofaboot-samples/sofaboot-sample-standard/app/biz/shared/src/main/resources/sofa-module.properties
sofaboot-samples/sofaboot-sample-standard/app/common/dal/pom.xml
sofaboot-samples/sofaboot-sample-standard/app/common/dal/src/main/java/com/alipay/sofa/common/dal/dai/NewManageDao.java
sofaboot-samples/sofaboot-sample-standard/app/common/dal/src/main/java/com/alipay/sofa/common/dal/daiimpl/INewManageDao.java
sofaboot-samples/sofaboot-sample-standard/app/common/dal/src/main/java/com/alipay/sofa/common/dal/dao/NewDO.java
sofaboot-samples/sofaboot-sample-standard/app/common/dal/src/main/resources/META-INF/spring/common-dal.xml
sofaboot-samples/sofaboot-sample-standard/app/common/dal/src/main/resources/sofa-module.properties
sofaboot-samples/sofaboot-sample-standard/app/common/service/facade/pom.xml
sofaboot-samples/sofaboot-sample-standard/app/common/service/facade/src/main/java/com/alipay/sofa/facade/NewReadService.java
sofaboot-samples/sofaboot-sample-standard/app/common/service/facade/src/main/java/com/alipay/sofa/facade/NewWriteService.java
sofaboot-samples/sofaboot-sample-standard/app/test/pom.xml
sofaboot-samples/sofaboot-sample-standard/app/test/src/test/java/com/alipay/sofa/test/base/AbstractTestBase.java
sofaboot-samples/sofaboot-sample-standard/app/test/src/test/java/com/alipay/sofa/test/usercases/JsonSampleControllerTest.java
sofaboot-samples/sofaboot-sample-standard/app/test/src/test/resources/test/META-INF/spring/test.xml
sofaboot-samples/sofaboot-sample-standard/app/web/pom.xml
sofaboot-samples/sofaboot-sample-standard/app/web/src/main/java/com/alipay/sofa/SOFABootWebApplication.java
sofaboot-samples/sofaboot-sample-standard/app/web/src/main/java/com/alipay/sofa/controller/SampleRestController.java
sofaboot-samples/sofaboot-sample-standard/app/web/src/main/resources/application.properties
sofaboot-samples/sofaboot-sample-standard/pom.xml

Add standard sample.

---

healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/service/SofaBootReadinessCheckEndpoint.java

Fix that SofaBootComponentHealthCheckInfo health status is influenced by HealthIndicator.

---

isle-sofa-boot-starter/pom.xml
isle-sofa-boot-starter/src/main/java/com/alipay/sofa/isle/spring/listener/SofaModuleBeanFactoryPostProcessor.java

fix SofaModuleBeanFactoryPostProcessor no beandefinition bug

---

healthcheck-sofa-boot-starter/pom.xml
infra-sofa-boot-starter/pom.xml
isle-sofa-boot-starter/pom.xml
pom.xml
runtime-sofa-boot-plugin/pom.xml
runtime-sofa-boot-starter/pom.xml
sofaboot-dependencies/pom.xml
sofaboot-samples/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/README.md
sofaboot-samples/sofaboot-sample-with-isle/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/service-consumer/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/service-facade/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/service-provider/pom.xml
sofaboot-samples/sofaboot-sample-with-isle/sofa-boot-run/pom.xml
sofaboot-samples/sofaboot-sample-with-isolation/pom.xml
sofaboot-samples/sofaboot-sample-with-rpc/README.md
sofaboot-samples/sofaboot-sample-with-rpc/pom.xml
sofaboot-samples/sofaboot-sample/pom.xml
test-sofa-boot-starter/pom.xml

Upgrade version to release 2.4.8.

Release 2.4.8

---

isle-sofa-boot-starter/src/main/java/com/alipay/sofa/isle/stage/SpringContextInstallStage.java

Add friendly hint.

---

sofaboot-dependencies/pom.xml

Manage zipkin version.

---

infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/env/EnvironmentCustomizer.java
runtime-sofa-boot-plugin/pom.xml

https://github.com/alipay/sofa-jarslink/issues/104

Fix multi biz invocation.

---

runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/annotation/PlaceHolderAnnotationInvocationHandler.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/annotation/PlaceHolderBinder.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/annotation/WrapperAnnotation.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/ServiceAnnotationBeanPostProcessor.java
runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/annotation/AnnotationSample.java
runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/annotation/AnnotationSampleTest.java
runtime-sofa-boot-starter/src/test/resources/config/application-annotation.properties

* support placeholder in SofaService and SofaReference annotation

Support placeholder in SofaService and SofaReference annotation. (#264)

---

runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/api/annotation/SofaReferenceBinding.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/api/annotation/SofaServiceBinding.java

+ Add serialize type 
+ Add load balancer
+ fix typo

Add SOFARPC annotation config

---

isle-sofa-boot-starter/src/main/java/com/alipay/sofa/isle/loader/DynamicSpringContextLoader.java
isle-sofa-boot-starter/src/main/java/com/alipay/sofa/isle/spring/factory/BeanLoadCostBeanFactory.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/component/impl/ComponentManagerImpl.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spi/component/ComponentManager.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spi/log/SofaLogger.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/factory/AbstractContractFactoryBean.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/factory/ReferenceFactoryBean.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/factory/ServiceFactoryBean.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/parser/AbstractContractDefinitionParser.java

pick 2.4.8 lost code

---

infra-sofa-boot-starter/src/main/resources/META-INF/com/alipay/sofa/infra/config/spring/namespace/schema/rpc.xsd
infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/config/spring/XsdValidationTest.java
infra-sofa-boot-starter/src/test/resources/config/spring/test_sofa_parameter.xml
infra-sofa-boot-starter/src/test/resources/config/spring/test_sofa_parameter_missing_key.xml
infra-sofa-boot-starter/src/test/resources/config/spring/test_sofa_parameter_outside_binding.xml
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/api/annotation/SofaParameter.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/api/annotation/SofaReferenceBinding.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/api/annotation/SofaServiceBinding.java

see #309 and alipay/sofa-rpc-boot-projects#136.

Parameter xsd and annotation

---

runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/ApplicationShutdownCallbackPostProcessor.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/ClientFactoryBeanPostProcessor.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/ReferenceAnnotationBeanPostProcessor.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/initializer/SofaRuntimeSpringContextInitializer.java
runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/integration/postprocessor/BeanPostProcessorOrderTest.java
runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/integration/postprocessor/BeanPostProcessorTestBean.java
runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/integration/postprocessor/HigherOrderBeanPostProcessor.java
runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/integration/postprocessor/LowOrderBeanPostProcessor.java
runtime-sofa-boot-starter/src/test/resources/META-INF/spring/test-postprocessor-order.xml
runtime-sofa-boot-starter/src/test/resources/config/application.properties

fix https://github.com/alipay/sofa-boot/issues/301

fix for bean post processor order

---

runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/common/xmap/XValueFactory.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/ext/client/ExtensionClientImpl.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/ext/component/ExtensionComponent.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/ext/component/ExtensionInternal.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/ext/component/ExtensionPointComponent.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/ext/component/ExtensionPointInternal.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/ext/spring/ExtensionBuilder.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/ext/spring/ExtensionPointBuilder.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/service/api/component/Extensible.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/service/api/component/Extension.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/service/api/component/ExtensionPoint.java
runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/integration/extension/ExtensionTest.java
runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/integration/extension/bean/IExtensionImpl.java
runtime-sofa-boot-starter/src/test/resources/META-INF/spring/test-extension.xml

- fix extension case stable
- move some package due to some compatible reasons

fix extension case stable

---

runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/ext/spring/ExtensionBuilder.java

delete unused method genericExtension

---

infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/autoconfigure/SofaBootInfraAutoConfiguration.java
infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/proxy/ProxyBeanFactoryPostProcessor.java
infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/proxy/ProxyFactoryBeanPostProcessor.java
infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/proxy/SofaProxyFactoryBean.java
infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/base/SofaBootWebSpringBootApplication.java
infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/proxy/ProxyConfiguration.java
infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/proxy/ProxyFactoryBeanTest.java
infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/proxy/SofaProxyFactoryBeanTest.java
infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/proxy/bean/ProxyTestBeanFacade.java
infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/proxy/bean/ProxyTestBeanImpl.java
infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/proxy/bean/ProxyTestPostProcessor.java
infra-sofa-boot-starter/src/test/resources/META-INF/sofaboot-web-test/proxy.xml
infra-sofa-boot-starter/src/test/resources/config/application-sofa-proxy.properties

Fix proxy factory bean issue

---

runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/annotation/PlaceHolderAnnotationInvocationHandler.java

Fix WrapperAnnotation is not visible from class loader.

---

runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/api/annotation/SofaMethod.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/api/annotation/SofaReferenceBinding.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/api/annotation/SofaServiceBinding.java

feature
https://github.com/alipay/sofa-boot/issues/387
https://github.com/alipay/sofa-rpc/issues/561

add method annotation for rpc

---

.gitignore
change_version.sh
sofaboot-samples/sofaboot-sample-with-isle/build.gradle
sofaboot-samples/sofaboot-sample-with-isle/gradle.properties
sofaboot-samples/sofaboot-sample-with-isle/service-consumer/build.gradle
sofaboot-samples/sofaboot-sample-with-isle/service-facade/build.gradle
sofaboot-samples/sofaboot-sample-with-isle/service-provider/build.gradle
sofaboot-samples/sofaboot-sample-with-isle/settings.gradle
sofaboot-samples/sofaboot-sample-with-isle/sofa-boot-run/build.gradle

Added configuration to use Gradle to build sample "sofaboot-sample-with-isle"

Added configuration to use gradle build

---

README.md

Update Travis CI Icon Address

---

README.md
infra-sofa-boot-starter/src/main/resources/banner.txt

Fix banner text configuration.

---

sofa-boot-project/sofaboot-dependencies/pom.xml

update bolt version to 1.5.6

---

sofa-boot-project/sofaboot-dependencies/pom.xml

Upgrade fastjson and jackson

---

sofa-boot-project/sofa-boot-plugins/runtime-sofa-boot-plugin/pom.xml

update runtime plugin upon 3.2.0 and above

---

sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/invoke/DynamicJvmServiceProxyFinder.java

fix dynamic invoke

---

sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/component/impl/StandardSofaRuntimeManager.java

Shutdown RuntimeShutdownAware first

---

sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/invoke/DynamicJvmServiceProxyFinder.java

fix skip jvm invoke

---

sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/component/ReferenceComponent.java

Support find service target from other biz

---

sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/container/ProviderConfigContainer.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/common/xmap/Path.java

use StringBuilder instead of StringBuffer in single-threaded local variable

---

sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/config/SofaBootRpcConfigConstants.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/config/SofaBootRpcProperties.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/container/ServerConfigContainer.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/adapter/HttpBindingAdapter.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/adapter/helper/ProviderConfigHelper.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/binding/HttpBinding.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/converter/HttpBindingConverter.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/param/HttpBindingParam.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/resources/META-INF/services/com.alipay.sofa.runtime.spi.binding.BindingAdapter
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/resources/META-INF/services/com.alipay.sofa.runtime.spi.service.BindingConverter
sofa-boot-project/sofa-boot-starters/rpc-sofa-boot-starter/src/main/resources/META-INF/services/com.alipay.sofa.runtime.spi.binding.BindingAdapter
sofa-boot-project/sofa-boot-starters/rpc-sofa-boot-starter/src/main/resources/META-INF/services/com.alipay.sofa.runtime.spi.service.BindingConverter

Publish the HTTP service using @SofaServiceBinding (#522)

---

sofa-boot-project/sofa-boot-starters/rpc-sofa-boot-starter/pom.xml
sofa-boot-project/sofaboot-dependencies/pom.xml

feat:update rest dep to 3.6.3

---

sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/invoke/DynamicJvmServiceProxyFinder.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/FinishStartupEventHandler.java
sofa-boot-project/sofa-boot-plugins/runtime-sofa-boot-plugin/src/main/java/com/alipay/sofa/runtime/ark/plugin/SofaRuntimeActivator.java

support invoke ark jvm service at startup phase

---

sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/container/ServerConfigContainer.java

fix https://github.com/sofastack/sofa-rpc/issues/810

fix:fix virtual host settings in http/http2

---

sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/container/SpringBridge.java

https://github.com/sofastack/sofa-boot/issues/570

SpringBridge Application null judgement

---

sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaRpcAutoConfiguration.java

fix 
https://github.com/sofastack/sofa-boot/issues/566#event-2910390177

fix:fix the bug of registry config

---

sofa-boot-project/sofaboot-dependencies/pom.xml

remove jaxrs api

---

sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/runtime/SofaRuntimeAutoConfiguration.java

disable StandardSofaRuntimeManager auto shutdown

---

sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/build.gradle
sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/pom.xml
sofa-boot-project/sofaboot-dependencies/pom.xml

fix: https://github.com/sofastack/sofa-boot/issues/609

update spring boot version to 2.1.13.RELEASE

---

sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaRpcAutoConfiguration.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/config/MulticastConfigurator.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/config/SofaBootRpcConfigConstants.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/container/MulticastConfiguratorTest.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/readiness/ReadinessTest.java
sofa-boot-project/sofaboot-dependencies/pom.xml

support multicast registry in sofa rpc .
Related issue:  https://github.com/sofastack/sofa-rpc/issues/781
Related PR:  https://github.com/sofastack/sofa-rpc/pull/875

support rpc multicast registry

---

sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaRpcAutoConfiguration.java

feat: rest auto registe

---

sofa-boot-project/sofaboot-dependencies/pom.xml

upgrade sofa ark version

---

sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/loader/DynamicSpringContextLoader.java
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/spring/listener/SofaModuleContextRefreshedListener.java
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/stage/AbstractPipelineStage.java
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/stage/SpringContextInstallStage.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/component/impl/ComponentManagerImpl.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/ext/component/ExtensionComponent.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/ext/spring/ExtensionFactoryBean.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/ext/spring/ExtensionPointFactoryBean.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/log/SofaLogger.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/binding/JvmBindingAdapter.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/component/ReferenceComponent.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/component/ServiceComponent.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/ServiceBeanFactoryPostProcessor.java
sofa-boot-project/sofa-boot-starters/tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/springmvc/SpringMvcFilterJsonOutputTest.java

modify SofaLogger implementation

---

sofa-boot-project/sofaboot-dependencies/pom.xml

fix https://github.com/sofastack/sofa-boot/issues/616
fix https://github.com/sofastack/sofa-boot/issues/620

Version control of sofa-ark-archive and update ark version

---

sofa-boot-project/sofaboot-dependencies/pom.xml

upgrade sofa common tools version

---

sofa-boot-project/sofa-boot-core/rpc-sofa-boot/pom.xml
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/config/SofaBootRpcConfigConstants.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/config/SofaBootRpcProperties.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/container/ServerConfigContainer.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/adapter/TripleBindingAdapter.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/binding/RpcBindingType.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/binding/TripleBinding.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/converter/TripleBindingConverter.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/param/TripleBindingParam.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/SofaBootRpcAllTest.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/bean/grpc/GrpcGreeterImpl.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/bean/triple/TripleGreeterImpl.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/resources/META-INF/services/com.alipay.sofa.runtime.spi.binding.BindingAdapter
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/resources/META-INF/services/com.alipay.sofa.runtime.spi.service.BindingConverter
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/resources/spring/test_all.xml
sofa-boot-project/sofa-boot-starters/rpc-sofa-boot-starter/src/main/resources/META-INF/services/com.alipay.sofa.runtime.spi.binding.BindingAdapter
sofa-boot-project/sofa-boot-starters/rpc-sofa-boot-starter/src/main/resources/META-INF/services/com.alipay.sofa.runtime.spi.service.BindingConverter
sofa-boot-project/sofa-boot/src/main/resources/com/alipay/sofa/boot/spring/namespace/schema/rpc.xsd

triple compatible for grpc
we delete grpc

feat:triple

---

sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/spring/share/SofaModulePostProcessorShareManager.java

SofaModulePostProcessorShareManager detect null parameter

---

sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/ReadinessCheckListener.java
sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/test/java/com/alipay/sofa/healthcheck/test/AfterHealthReadinessCheckCallbackTest.java
sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/test/java/com/alipay/sofa/healthcheck/test/bean/FailedHealthCheck.java
sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/test/java/com/alipay/sofa/healthcheck/test/bean/SuccessHealthCheck.java

fix: https://github.com/sofastack/sofa-boot/issues/629

ReadinessCheckCallback when health check paas

---

sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/converter/RpcBindingConverter.java

fix：https://github.com/sofastack/sofa-rpc/issues/614

fix:fix callback of bolt

---

sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/component/ReferenceComponent.java

fix: https://github.com/sofastack/sofa-boot/issues/646

remove reference component redundant removeService

---

sofa-boot-project/sofa-boot-actuator-autoconfigure/src/main/java/com/alipay/sofa/boot/actuator/autoconfigure/health/SofaBootHealthCheckAutoConfiguration.java
sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/HealthCheckException.java
sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/HealthCheckProperties.java
sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/ReadinessCheckListener.java
sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/test/java/com/alipay/sofa/healthcheck/test/AfterHealthReadinessCheckCallbackTest.java
sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/test/java/com/alipay/sofa/healthcheck/test/HealthCheckConfigurationTest.java
sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/test/java/com/alipay/sofa/healthcheck/test/HealthCheckInsulatorTest.java
sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/test/java/com/alipay/sofa/healthcheck/test/HealthCheckerProcessorTest.java
sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/test/java/com/alipay/sofa/healthcheck/test/HealthIndicatorCheckProcessorTest.java
sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/test/java/com/alipay/sofa/healthcheck/test/ReactiveHealthIndicatorTest.java
sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/test/java/com/alipay/sofa/healthcheck/test/ReadinessCheckListenerTest.java
sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/test/resources/application-health.properties

fix: https://github.com/sofastack/sofa-boot/issues/648

add switch for terminating app when health check fails

---

sofa-boot-project/sofa-boot-core/rpc-sofa-boot/pom.xml

chore:update grpc and protoc version

chore:update grpc and protoc version

---

sofa-boot-project/sofa-boot-actuator-autoconfigure/src/main/java/com/alipay/sofa/boot/actuator/autoconfigure/health/SofaBootHealthCheckAutoConfiguration.java
sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/health/ComponentHealthIndicator.java
sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/impl/ComponentHealthChecker.java
sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/test/java/com/alipay/sofa/healthcheck/test/HealthCheckerProcessorTest.java
sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/test/java/com/alipay/sofa/healthcheck/test/TestComponent.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/aware/DefaultRuntimeShutdownAware.java

fix: https://github.com/sofastack/sofa-boot/issues/656

component health check display failed first

---

sofa-boot-project/sofaboot-dependencies/pom.xml

fix: https://github.com/sofastack/sofa-boot/issues/665

update fastjson to 1.2.69

---

sofa-boot-project/sofaboot-dependencies/pom.xml

upgrade-ark-version-1.1.4

---

sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/misc/MethodElementInterface.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/misc/MethodElementInterfaceImpl.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/misc/XsdTimeoutTest.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/resources/spring/service_reference.xml
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/ClientFactoryTest.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/spi/component/AbstractComponentTest.java

add tests for ServiceClient#removeService, ReferenceClient#removeReference, AbstractComponent#isHealthy, RpcBindingConverter#parseMethod methods

Add factory and component tests

---

sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/container/ServerConfigContainer.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/container/ServerConfigContainerTest.java

fix: https://github.com/sofastack/sofa-boot/issues/708

fix bug: wrong max and core size of thread pool  in http config

---

sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/ext/component/ExtensionPointImpl.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/ext/spring/SpringExtensionPointImpl.java

fix: https://github.com/sofastack/sofa-boot/issues/713

Fix extension point race condition

---

sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/binding/JvmBindingAdapter.java

fix: https://github.com/sofastack/sofa-boot/issues/717

fix jvm filter npe bug

---

sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spi/util/ParserUtils.java

change getBoolean to parseBoolean in ParserUtils

---

sofa-boot-project/sofa-boot-actuator-autoconfigure/src/main/java/com/alipay/sofa/boot/actuator/autoconfigure/health/SofaBootHealthCheckAutoConfiguration.java

allow-close-isle-health

---

sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/spring/factory/BeanLoadCostBeanFactory.java
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/stage/ModuleLogOutputStage.java
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/ApplicationRuntimeModelTest.java
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/BeanHierarchyTest.java
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/service/Child1.java
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/service/Child2.java
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/service/Child3.java
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/service/GrandChild1.java
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/service/GrandChild2.java
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/service/GrandChild3.java
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/service/IService.java
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/service/ServiceImpl.java
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/resources/module/META-INF/spring/beans.xml
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/resources/module/sofa-module.properties

fix: https://github.com/sofastack/sofa-boot/issues/730

BeanLoadCost hierarchical display

---

sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/PostProcessorShareTest.java

clean sofa-boot-samples module

---

sofa-boot-project/sofa-boot-core/tracer-sofa-boot/src/main/java/com/alipay/sofa/tracer/boot/flexible/processor/SofaTracerMethodInvocationProcessor.java

bugfix: tracer miss context

---

sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/deployment/impl/FileDeploymentDescriptor.java
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/FileDeploymentDescriptorWhiteSpacePathTest.java
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/resources/white space/META-INF/spring/beans.xml
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/resources/white space/sofa-module.properties

fix: https://github.com/sofastack/sofa-boot/issues/768

Fix FileDeploymentDescriptor white space not recognizing bug

---

sofa-boot-project/sofaboot-dependencies/pom.xml

fix: https://github.com/sofastack/sofa-boot/issues/776

Update tomcat version to 9.0.37

---

sofa-boot-project/sofa-boot-core/log-sofa-boot/src/main/java/com/alipay/sofa/boot/logging/LogEnvironmentPreparingListener.java

fix: https://github.com/sofastack/sofa-boot/issues/806

Fix sofa.middleware.log.console overridden problem

---

sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/ServiceBeanFactoryPostProcessor.java

fix: https://github.com/sofastack/sofa-boot/issues/835

fix annotation processing TypeNotPresentExceptionProxy bug

---

.github/workflows/maven.yml
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/util/SeparateClassLoaderTestRunner.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/binding/RpcBinding.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/binding/RpcBindingMethodInfo.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/param/RpcBindingParam.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/SofaBootRpcAllTest.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/bean/generic/GenericParamModel.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/bean/generic/GenericResultModel.java
sofa-boot-project/sofa-boot-parent/pom.xml
sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/src/main/java/org/springframework/boot/gradle/plugin/SofaBootPlugin.java
sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/src/test/java/org/springframework/boot/gradle/junit/GradleCompatibilitySuite.java

fix: https://github.com/sofastack/sofa-boot/issues/838

Upgrade JDK version to 11

---

sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/converter/RpcBindingConverter.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/SofaBootRpcAllTest.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/bean/annotation/AnnotationService.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/bean/annotation/AnnotationServiceImpl.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/bean/annotation/AnnotationServiceTimeoutImpl.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/api/annotation/SofaReferenceBinding.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/api/annotation/SofaServiceBinding.java

adjust timeout priority
https://github.com/sofastack/sofa-rpc/issues/1036

adjust timeout priority

---

sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/stage/SpringContextInstallStage.java

fix: https://github.com/sofastack/sofa-boot/issues/865

Fix thread pool queue configuration when application context refreshing

---

pom.xml

Update SpringBoot version 2.3.12

---

pom.xml

update sofaboot 3.11.1

---

pom.xml

Fix https://tanzu.vmware.com/security/cve-2022-22970

update springframework to 5.3.20

---

sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/core/HealthCheckerComparatorProvider.java
sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/util/HealthCheckUtils.java
sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/test/java/com/alipay/sofa/healthcheck/test/HealthCheckUtilsTest.java

support custom HealthCheckerComparator

---

sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/stage/SpringContextInstallStage.java

add a minor changes to log the missing modules in SpringContextInstallStage

add a minor changes to log the missing modules in SpringContextInstallStage

---

.github/workflows/release.yml
pom.xml

This action will release jar to. staging repository.

Add github action for release jar

---

.github/workflows/maven.yml
.github/workflows/release.yml
pom.xml
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/pom.xml
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/common/xmap/DOMSerializer.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/common/xmap/XAnnotatedContent.java
sofa-boot-project/sofa-boot-parent/pom.xml
sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/build.gradle
sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/gradle/wrapper/gradle-wrapper.properties
sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/test/spring/XsdValidationTest.java
sofa-boot-project/sofaboot-dependencies/pom.xml

1. Upgrade supported JDK version to 17
2. Use xerces replace jdk internal package

Upgrade compile JDK version to 17

---

sofa-boot-project/sofa-boot-autoconfigure/pom.xml
sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/ConsulRegistryConfiguration.java
sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/LocalRegistryConfiguration.java
sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/MeshRegistryConfiguration.java
sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/MulticastRegistryConfiguration.java
sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/NacosRegistryConfiguration.java
sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/RegistryConfigurations.java
sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/RestFilterConfiguration.java
sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaRegistryConfiguration.java
sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaRpcAutoConfiguration.java
sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/SwaggerConfiguration.java
sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/ZookeeperRegistryConfiguration.java
sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/package-info.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/config/SofaBootRpcProperties.java

rpc auto configuration refactor

rpc auto configuration refactor

---

sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/RestFilterConfiguration.java
sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaRpcAutoConfiguration.java
sofa-boot-project/sofa-boot-autoconfigure/src/test/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaRpcAutoConfigurationTests.java

rpc auto configuration test case

rpc auto configuration test case

---

sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/test/java/com/alipay/sofa/rpc/boot/test/config/DefaultTracingTest.java
sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/test/java/com/alipay/sofa/rpc/boot/test/config/SofaRpcLoggerLevelConfigTest.java
sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/test/java/com/alipay/sofa/rpc/boot/test/readiness/ReadinessTest.java
sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/test/java/com/alipay/sofa/rpc/boot/test/reference/ReferenceTest.java
sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/test/java/com/alipay/sofa/tests/rpc/boot/SofaBootRpcApplicationTests.java
sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/test/java/com/alipay/sofa/tests/rpc/mesh/MeshTest.java
sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/test/java/com/alipay/sofa/tests/rpc/misc/XsdTimeoutTest.java

rpc smoke tests modify

---

sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/components/ComponentsEndPoint.java
sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/startup/StartupReporter.java

(cherry picked from commit 9930d16da870f2ec21455037e3a9615e76e4f307)

Fix components end point (#1078)

---

pom.xml
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/boot/isle/loader/DynamicSpringContextLoader.java
sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/context/SofaGenericApplicationContext.java
sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/context/SofaGenericApplicationContextTests.java
sofa-boot-project/sofaboot-dependencies/pom.xml

2. addPostProcessors avoid duplicate

1. update springboot 3.0.4

---

pom.xml
sofa-boot-project/sofa-boot-actuator-autoconfigure/pom.xml
sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/components/SofaBootComponentsEndPoint.java
sofa-boot-project/sofa-boot-autoconfigure/src/test/java/com/alipay/sofa/autoconfigure/test/runtime/SofaRuntimePropertiesTest.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/SofaRuntimeProperties.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/configure/SofaRuntimeConfigurationProperties.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/ext/component/ExtensionComponent.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/ext/component/ExtensionPointComponent.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/ext/spring/ExtensionFactoryBean.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/ext/spring/ExtensionPointFactoryBean.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/component/ReferenceComponent.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/component/ServiceComponent.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/helper/ReferenceRegisterHelper.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spi/component/AbstractComponent.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spi/component/ComponentDefinitionInfo.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/ReferenceAnnotationBeanPostProcessor.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/factory/ReferenceFactoryBean.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/factory/ServiceFactoryBean.java
sofa-boot-project/sofa-boot-parent/pom.xml
sofa-boot-project/sofa-boot-starters/runtime-sofa-boot-starter/pom.xml

1.componentinfo add more details for components endpoint.
2.reference check support skip by interface & uniqueId

Feature same module inject

---

sofa-boot-project/sofa-boot-autoconfigure/pom.xml
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/pom.xml
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/SofaEventHandlerTest.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
sofa-boot-project/sofa-boot-core/startup-sofa-boot/pom.xml
sofa-boot-project/sofa-boot-parent/pom.xml

SofaEventHandlerTest use mockito

SofaEventHandlerTest use mockito

---

sofa-boot-project/sofa-boot-autoconfigure/src/test/java/com/alipay/sofa/autoconfigure/test/runtime/SofaRuntimePropertiesTest.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/SofaRuntimeProperties.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/configure/SofaRuntimeConfigurationProperties.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/component/ReferenceComponent.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spi/component/ComponentDefinitionInfo.java

reference component health check support more deails when failed

reference component health check support more deails when failed

---

sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/api/annotation/SofaService.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/api/annotation/SofaServices.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/ServiceBeanFactoryPostProcessor.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/RepeatableSofaServiceTest.java

Support repeatable @SofaServices annotation

---

sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/BeanPostProcessorOrderTest.java

fix BeanPostProcessorOrderTest testShutDownHookReordered

fix BeanPostProcessorOrderTest testShutDownHookReordered

---

sofa-boot-project/sofaboot-dependencies/pom.xml

javassit upgrade version 3.28.0-GA

javassit upgrade version 3.28.0-GA

---

sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/api/annotation/SofaServiceBean.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/ServiceBeanTest.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/beans/service/SofaServiceBeanService.java
sofa-boot-project/sofa-boot-core/startup-sofa-boot/src/test/java/com/alipay/sofa/startup/test/IsleCheckStartupReporterTest.java

add @SofaServiceBean annotation to create a SOFA service and also created a bean.

Add annotation sofa service bean

---

sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/boot/isle/ApplicationRuntimeModel.java
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/boot/isle/deployment/AbstractDeploymentDescriptor.java
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/boot/isle/deployment/DefaultModuleDeploymentValidator.java
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/boot/isle/stage/ModelCreatingStage.java
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/boot/isle/ApplicationRuntimeModelTests.java
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/boot/isle/deployment/DefaultModuleDeploymentValidatorTests.java
sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-isle/src/main/resources/nospring-module/sofa-module.properties
sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-isle/src/main/resources/nospringchild-module/META-INF/spring/service.xml
sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-isle/src/main/resources/nospringchild-module/sofa-module.properties
sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-isle/src/test/java/com/alipay/sofa/smoke/tests/isle/DefaultSofaModuleProfileCheckerIntegrationTests.java

2. split loadPropertiesFormUrlResource method
3. remove require modules if module is none spring powered

1. distinct requrie modules

---

pom.xml

release 3.19.0

---

pom.xml
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/ServiceBeanFactoryPostProcessor.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/RepeatableSofaServiceTest.java
sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/util/SmartAnnotationUtils.java
sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/test/util/SmartAnnotationUtilsTest.java

2. fix @SofaService Annotation parse

1. update version 3.18.1

---

pom.xml

release_3.19.1

---

pom.xml
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/SofaRuntimeProperties.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/configure/SofaRuntimeConfigurationProperties.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/component/ServiceComponent.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/ServiceBeanFactoryPostProcessor.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/ServiceDuplicateTest.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/beans/service/ClientFactoryBean.java
sofa-boot-project/sofa-boot/src/main/resources/sofa-boot/log-codes.properties

Support sofa service duplicate configurable

Support sofa service duplicate configurable

---

sofa-boot-project/sofaboot-dependencies/pom.xml

1. update rpc 5.11.0
2. update hessian 3.5.0
3. update sofark 2.2.2

Update sofa stack component versions

---

pom.xml
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/boot/isle/stage/SpringContextInstallStage.java

2. fix SpringContextInstallStage countDownLatch size error

1. update 4.0.2

---

sofa-boot-project/sofa-boot-actuator-autoconfigure/pom.xml

add spring-boot-configuration-processor in sofa-boot-actuator-autoconigure model

add spring-boot-configuration-processor in sofa-boot-actuator-autoconigure model

---

sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/KubernetesRegistryConfiguration.java
sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/RegistryConfigurations.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/config/KubernetesConfigurator.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/config/SofaBootRpcConfigConstants.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/config/KubernetesConfiguratorTest.java

Support kubernetes registry configuration, related https://github.com/sofastack/sofa-rpc/pull/1395

Support kubernetes registry configuration

---

.github/workflows/cloud_code_scan.yml

Motivation:
为了增强代码审查流程并确保代码的安全性和合规性，我新增了代码安全扫描和开源组件扫描。通过加入这些扫描，我们可以识别潜在的漏洞，并确保代码库符合开源项目治理标准化的要求。
Modification:
新增了cloud_code_scan.yml模板，添加了代码安全扫描和开源组件扫描步骤。这些步骤将作为工作流的一部分进行执行，以执行必要的安全检查和合规性验证。通过添加这些扫描，我们可以积极解决安全问题，并确保遵守开源许可协议。
Result:
通过引入代码安全扫描和开源组件扫描，增强了代码审查流程。它有助于识别安全漏洞，并确保符合开源许可要求。这一改进有助于提高代码库的整体质量和安全性。

Add Code Scan Action

---

sofa-boot-project/sofa-boot-core/startup-sofa-boot/src/main/java/com/alipay/sofa/startup/stage/StartupSpringApplicationRunListener.java

increase StartupSpringApplicationRunListener order (-10)

increase StartupSpringApplicationRunListener order
