isle-sofa-boot-starter/src/test/java/com/alipay/sofa/isle/ServiceAnnotationBeanPostProcessorTest.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/ServiceAnnotationBeanPostProcessor.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/configuration/SofaRuntimeAutoConfiguration.java
runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/spring/config/SofaRuntimePropertiesTest.java

Use the applicationContext to load the SofaRuntimeProperties to avoid premature initialization

---

pom.xml

升级 maven-javadoc-plugin 插件版本由之前的 2.9.1 到 2.10.1，以修复在 Mac OSX 下可能出现如下报错：
> Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.9.1:jar (attach-javadocs) on project infra-sofa-boot-starter: MavenReportException: Error while creating archive: Unable to find javadoc command: The environment variable JAVA_HOME is not correctly set. -> [Help 1]

Update maven-javadoc-plugin version to 2.10.1.(#133)

---

sofaboot-dependencies/pom.xml

Upgrade sofa-bolt to version `1.4.2`  recently released
[sofa-bolt release notes](https://github.com/alipay/sofa-bolt/releases)
[sofa-bolt](https://github.com/alipay/sofa-bolt) version `1.4.2` have released and the bolt version should be governanced by  SOFABoot.
Fixes #140

Upgrade sofa-bolt version to 1.4.2

---

healthcheck-sofa-boot-starter/pom.xml
infra-sofa-boot-starter/pom.xml
isle-sofa-boot-starter/pom.xml
runtime-sofa-boot-starter/pom.xml

Add sofa-version-maven-plugin for SOFABoot starters.

Add sofa-version-maven-plugin for SOFABoot starters.

---

healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/service/EndPointConfig.java
healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/service/SofaBootReadinessCheckEndpoint.java
healthcheck-sofa-boot-starter/src/test/java/com/alipay/sofa/healthcheck/base/AbstractTestBase.java
healthcheck-sofa-boot-starter/src/test/java/com/alipay/sofa/healthcheck/base/SpringBootWebApplication.java
healthcheck-sofa-boot-starter/src/test/java/com/alipay/sofa/healthcheck/enable/SofaBootReadinessCheckEnableTest.java
healthcheck-sofa-boot-starter/src/test/java/com/alipay/sofa/healthcheck/enable/SofaBootReadinessCheckUnableTest.java
healthcheck-sofa-boot-starter/src/test/resources/application-disable.properties
healthcheck-sofa-boot-starter/src/test/resources/application.properties

SOFABoot add configuration `com.alipay.sofa.healthcheck.enabled` to disable readiness check
Add  `com.alipay.sofa.healthcheck.enabled` configuration for disable readiness check.
Fixes #153

SOFABoot add configuration com.alipay.sofa.healthcheck.enabled to disable readiness check

---

isle-sofa-boot-starter/src/main/java/com/alipay/sofa/isle/loader/DynamicSpringContextLoader.java
isle-sofa-boot-starter/src/test/java/com/alipay/sofa/isle/integration/IntegrationTest.java
isle-sofa-boot-starter/src/test/java/com/alipay/sofa/isle/integration/SofaBootTestApplication.java
isle-sofa-boot-starter/src/test/java/com/alipay/sofa/isle/integration/SofaBootTestAutoConfiguration.java
isle-sofa-boot-starter/src/test/java/com/alipay/sofa/isle/processor/SampleBeanPostProcessor.java
isle-sofa-boot-starter/src/test/java/com/alipay/sofa/isle/scan/SampleService.java
isle-sofa-boot-starter/src/test/java/com/alipay/sofa/isle/scan/SampleServiceImpl.java
isle-sofa-boot-starter/src/test/resources/META-INF/spring/test-service.xml
isle-sofa-boot-starter/src/test/resources/config/application.properties

Check whether it is neccessary when copy BeanPostProcessors and BeanFactoryPostProcessors from Root Application Context to SOFA Module.

Check whether it is neccessary when copy BeanPostProcessors and BeanFactoryPostProcessors from Root Application Context to SOFA Module

---

runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/integration/invoke/DynamicJvmServiceProxyFinder.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/service/binding/JvmBindingAdapter.java

fix throw object

---

infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/autoconfigure/SofaBootInfraAutoConfiguration.java
infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/env/EnvironmentCustomizer.java
isle-sofa-boot-starter/src/main/java/com/alipay/sofa/isle/constants/SofaModuleFrameworkConstants.java
isle-sofa-boot-starter/src/main/java/com/alipay/sofa/isle/stage/AbstractPipelineStage.java
isle-sofa-boot-starter/src/test/java/com/alipay/sofa/isle/DeploymentExceptionTest.java

 Provide friendly notice when the property of spring.application.name is missing.

---

isle-sofa-boot-starter/src/main/java/com/alipay/sofa/isle/spring/configuration/SofaModuleAutoConfiguration.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spi/spring/SofaRuntimeContextAware.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/SofaRuntimeContextAwareProcessor.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/configuration/SofaRuntimeAutoConfiguration.java

Optimize auto-configuration.

---

infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/env/EnvironmentCustomizer.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/initializer/SofaRuntimeSpringContextInitializer.java

SofaLogger is recommended way to log message in SOFABoot. It may leads linkage error when use SofaRuntimeLoggerFactory in ark container.

Fix logger linkage error.

---

healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/service/ReadinessEndpointWebExtension.java
healthcheck-sofa-boot-starter/src/test/java/com/alipay/sofa/healthcheck/usercases/HealthEndpointDefaultConfigurationTest.java

Fix readiness check details lost:

Fix readiness check details lost

---

runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/annotation/PlaceHolderAnnotationInvocationHandler.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/annotation/PlaceHolderBinder.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/annotation/WrapperAnnotation.java
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/ServiceAnnotationBeanPostProcessor.java
runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/annotation/AnnotationSample.java
runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/annotation/AnnotationSampleTest.java
runtime-sofa-boot-starter/src/test/resources/config/application-annotation.properties

Support placeholder in SofaService and SofaReference annotation.

---

.gitignore
runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/factory/AbstractContractFactoryBean.java
runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/integration/IntegrationTest.java
runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/integration/TestSofaServiceAndReferenceException.java

It seems that 2.x lost this part of the logic, causing the provider created with `@SofaService` lost the bindings.
--------
WIP:

add missing apiType logic

---

sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/xsd/WhateverClass.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/xsd/WhateverInterface.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/xsd/XsdTimeoutTest.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/resources/spring/xsd.xml
sofa-boot-project/sofa-boot/src/main/resources/com/alipay/sofa/boot/spring/namespace/schema/rpc.xsd

change xsd timeout from int to string

---

sofa-boot-project/sofa-boot-core/rpc-sofa-boot/pom.xml
sofa-boot-project/sofaboot-dependencies/pom.xml

update dubbo 2.6.7
dubbo 低版本时间比较久，存在一些兼容问题，目前rpc已经在5.6.4中升级，因为sofaboot同时升级

chore:update dubbo version

---

sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/impl/ComponentHealthChecker.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/misc/ComponentHealthCheckerTest.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/misc/WhateverClass.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/misc/WhateverInterface.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/misc/XsdTimeoutTest.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/xsd/XsdTimeoutTest.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/resources/spring/service_reference.xml
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/binding/JvmBinding.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/binding/JvmBindingAdapter.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/component/ReferenceComponent.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/component/ServiceComponent.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spi/component/AbstractComponent.java

see https://github.com/sofastack/sofa-boot/issues/534

Healthcheck improvement

---

sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/RuntimeContextBeanFactoryPostProcessor.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/BeanPostProcessorOrderTest.java

fix: https://github.com/sofastack/sofa-boot/issues/579

Removing register system beanPostProcessor

---

sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/health/MultiApplicationHealthIndicator.java
sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/impl/SofaRuntimeHealthChecker.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/invoke/DynamicJvmServiceProxyFinder.java

fix: https://github.com/sofastack/sofa-boot/issues/583

Fix MultiApplicationHealthIndicator stack overflow bug

---

sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/adapter/BindingAdapterFactoryTest.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/adapter/XBindingAdapter.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/adapter/XBindingAdapter2.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/adapter/XBindingAdapter3.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/converter/RpcBindingConverterTest.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/converter/TestBindingConverter.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/converter/TestBindingConverter2.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/converter/TestBindingConverter3.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/resources/META-INF/services/com.alipay.sofa.runtime.spi.binding.BindingAdapter
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/resources/META-INF/services/com.alipay.sofa.runtime.spi.service.BindingConverter
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/impl/BindingAdapterFactoryImpl.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/impl/BindingConverterFactoryImpl.java
sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/pom.xml

use @Order annotation to sort BindingAdapter or BindingConverter in factory, so that users can easily override them. 
When get object from factory(BindingAdapterFactory or  BindingConverterFactory ),users will get the object who has highest precedence
fix #543

Sort BindingAdapter and BindingConverter so that users can easily override them

---

sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaRpcAutoConfiguration.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/config/SofaBootRpcProperties.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/container/ConsumerConfigContainer.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/adapter/RpcBindingAdapter.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/adapter/helper/ConsumerConfigHelper.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/adapter/processor/ConsumerConfigProcessor.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/adapter/processor/ConsumerMockProcessor.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/adapter/processor/DynamicConfigProcessor.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/adapter/processor/ProcessorContainer.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/adapter/processor/ProviderConfigProcessor.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/binding/RpcBindingXmlConstants.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/converter/RpcBindingConverter.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/param/RpcBindingParam.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/SofaRpcTestAutoConfiguration.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/mock/HttpMockServer.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/mock/MockBeanConfigTest.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/mock/xml/XmlConfigTest.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/readiness/ReadinessTest.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/runtime/adapter/processor/ConsumerMockProcessorTest.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/runtime/adapter/processor/DynamicConfigProcessorTest.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/runtime/adapter/processor/ProcessorAutoConfigTest.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/resources/spring/test_only_mock.xml
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/resources/spring/test_only_mock_bean.xml
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/api/annotation/SofaReferenceBinding.java
sofa-boot-project/sofa-boot/src/main/resources/com/alipay/sofa/boot/spring/namespace/schema/rpc.xsd
sofa-boot-project/sofaboot-dependencies/pom.xml

Support use xml or annotation to set bolt mock.
For example:
```xml 
<sofa:reference id="xmlLocalMock" interface="com.alipay.sofa.rpc.boot.test.bean.invoke.HelloSyncService" repeatReferLimit="10">
<sofa:binding.bolt>
<sofa:global-attrs mock-bean="mockHello" mock-mode="local"/>
</sofa:binding.bolt>
</sofa:reference>
<sofa:reference id="xmlRemoteMock" interface="com.alipay.sofa.rpc.boot.test.bean.invoke.HelloSyncService" repeatReferLimit="10">
<sofa:binding.bolt>
<sofa:global-attrs mock-mode="remote"/>
<sofa:parameter key="mockUrl" value="http://127.0.0.1:1236/"/>
</sofa:binding.bolt>
</sofa:reference>
```
and 
```java
@SofaReference(binding = @SofaReferenceBinding(bindingType = "bolt", mockMode = MockMode.LOCAL, mockBean = "mockHello"))
private HelloSyncService     helloSyncService; …
```

support mock setting

---

sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/invoke/DynamicJvmServiceProxyFinder.java

fix: https://github.com/sofastack/sofa-boot/issues/699

fix ark jvm invoke bug

---

sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/common/RpcThreadPoolMonitor.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/container/ServerConfigContainer.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/log/LoggerConstant.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/resources/com/alipay/sofa/rpc/boot/log/log4j/log-conf.xml
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/resources/com/alipay/sofa/rpc/boot/log/log4j2/log-conf.xml
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/resources/com/alipay/sofa/rpc/boot/log/logback/log-conf.xml
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/common/ThreadPoolMonitorTest.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/config/DisableTracingTest.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/resources/config/application.properties
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/resources/logback.xml
sofa-boot-project/sofaboot-dependencies/pom.xml

feat: support triple thread monitor.

feat: support triple thread monitor

---

sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/util/NamedThreadFactory.java

NamedThreadFactory implements ThreadFactory , but the newThread method missed the @Override annotation

Add @Override annotation to NewThread of NamedThreadFactory

---

sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/config/SofaBootRpcConfigKeys.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/container/RegistryConfigContainer.java

Rpc-starter use sofa-common-tools's SofaConfig instead of System.getProperty

Rpc-starter use sofa-common-tools's SofaConfig instead of System.getProperty

---

sofa-boot-project/sofaboot-dependencies/pom.xml

fix: https://github.com/sofastack/sofa-boot/issues/829

Fix grpc version problem

---

sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/HealthCheckerProcessor.java
sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/HealthIndicatorProcessor.java
sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/core/HealthCheckExecutor.java
sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/core/HealthChecker.java
sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/impl/ComponentHealthChecker.java
sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/impl/ModuleHealthChecker.java
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/stage/SpringContextInstallStage.java
sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/constant/SofaBootConstants.java

fix #837 
1. 在检查前输出了`HealthChecker`的数量和名称，其中名称是通过调用`HealthChecker.getComponentName`方法获取的
1. 在指定HealthChecker检查前，输出了check start日志
1. 在检查前输出了`HealthIndicator`的数量和名称，其中名称使用的是beanId
1. 在指定HealthIndicator检查前，输出了check start日志
超时基于线程池实现:
1. 健康检查任务提交到线程池
1. 通过`Future.get(timeout)`等待检查结果
1. 超时(TimeoutException)则认为检查失败，且健康状态为未知(`Status.UNKNOWN`)
`HealthChecker`接口增加了`getTimeout`方法，用于获取超时时间。超时时间小于等于0时，使用默认的超时时间。
`HealthIndicator`超时时间通过配置属性获取。未配置超时时间，或配置的超时时间小于等于0时，使用默认的超时时间。
配置属性的key遵循格式: `com.alipay.sofa.healthcheck.indicator.timeout.${beanId}`。
```
com.alipay.sofa.healthcheck.default.timeout=60000
com.alipay.sofa.healthcheck.component.timeout=10000
com.alipay.sofa.healthcheck.module.timeout=10000
com.alipay.sofa.healthcheck.indicator.timeout.${beanId}=
```

Improve HealthCheck: add progress and timeout.(#837)

---

sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/AfterBizStartupEventHandler.java

AfterBizStartupEventHandler 和 SofaBizHealthCheckEventHandler 优先级一样，biz 启动失败时，会导致报错 com.alipay.sofa.runtime.invoke.DynamicJvmServiceProxyFinder#afterBizStartup NullPointException

adjust priority for AfterBizStartupEventHandler

---

sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/runtime/SofaRuntimeAutoConfiguration.java
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/loader/DynamicSpringContextLoader.java
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/FailModuleTest.java
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/PostProcessorShareTest.java
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/SingletonProcessorTest.java
sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/processor/SingletonBeanPostProcessor.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/RuntimeTestConfiguration.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/proxy/ProxyBeanFactoryPostProcessor.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/JvmFilterPostProcessor.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/RuntimeContextBeanFactoryPostProcessor.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/ServiceBeanFactoryPostProcessor.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/SofaShareBeanFactoryPostProcessor.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/share/SofaPostProcessorShareManager.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/singleton/SingletonSofaPostProcessor.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/configuration/RuntimeConfiguration.java
sofa-boot-project/sofa-boot-core/startup-sofa-boot/src/test/java/com/alipay/sofa/startup/test/configuration/SofaStartupIsleAutoConfiguration.java
sofa-boot-project/sofa-boot-core/startup-sofa-boot/src/test/java/com/alipay/sofa/startup/test/spring/RuntimeConfiguration.java

1. 支持通过 @SingletonSofaPostProcessor 注解指定 PostProcessor 以单例形式共享；
2. 优化一些 PostProcessor 实现，减少 byType 注入，避免触发 FactoryBean 提前初始化

Support singleton PostProcessor

---

pom.xml
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/ServiceBeanFactoryPostProcessor.java
sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/util/BeanDefinitionUtil.java

1. Update 3.16.1
2. Update ServiceBeanFactoryPostProcessor implement BeanFactoryPostProcessor and Ordered
3. Update BeanDefinitionUtil getTargetType

Release 3.16.1

---

sofa-boot-project/sofaboot-dependencies/pom.xml
sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/main/resources/META-INF/sofa-rpc/rpc-config.json

upgrade javassit version to 3.29.2-GA ,rpc smoke tests use javassist

upgrade javassit version to 3.29.2-GA ,rpc smoke tests use javassist

---

sofa-boot-project/sofa-boot-core/log-sofa-boot/src/main/java/com/alipay/sofa/boot/logging/LogEnvironmentPreparingListener.java
sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/listener/SofaConfigSourceSupportListener.java

raise SofaConfigSourceSupportListener order to "LoggingApplicationListener.DEFAULT_ORDER - 10" to fix toolkit-common-logging config bug

fix toolkit-common-logging config bug

---

pom.xml
sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/util/ApplicationListenerOrderConstants.java

fix_SofaTracerConfigurationListener_order

fix_SofaTracerConfigurationListener_order

---

.github/workflows/maven.yml
pom.xml
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/ServiceBeanFactoryPostProcessor.java
sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/bean/LocalVariableTableParameterNameDiscoverer.java
sofa-boot-project/sofaboot-dependencies/pom.xml
sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/main/java/com/alipay/sofa/smoke/tests/rpc/boot/RpcSofaBootApplication.java
sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-tracer/pom.xml

1. add legacy LocalVariableTableParameterNameDiscoverer
2. remove mysql-connector-java dpm

Update springboot 3.2.0

---

sofa-boot-project/sofa-boot-core/ark-sofa-boot/src/main/java/com/alipay/sofa/boot/ark/invoke/DynamicJvmServiceProxyFinder.java
sofa-boot-project/sofa-boot-core/ark-sofa-boot/src/test/java/com/alipay/sofa/boot/ark/MockBizManagerService.java

使用`getBizByClassLoader` 方法替换`getBizInOrder`方法。减少 Map.toArray 调用次数，和冗余的排序操作；

optimize getBiz method by reduce invoke Map.toArray() (#1286)

---

sofa-boot-project/sofa-boot-actuator-autoconfigure/src/main/java/com/alipay/sofa/boot/actuator/autoconfigure/rpc/RpcActuatorAutoConfiguration.java
sofa-boot-project/sofa-boot-actuator-autoconfigure/src/test/java/com/alipay/sofa/boot/actuator/autoconfigure/rpc/RpcActuatorAutoConfigurationTests.java
sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/extension/ProviderConfigDelayRegisterCheckerSupport.java
sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/rpc/HealthCheckProviderConfigDelayRegisterChecker.java
sofa-boot-project/sofa-boot-actuator/src/test/java/com/alipay/sofa/boot/actuator/rpc/HealthCheckProviderConfigDelayRegisterCheckerTest.java
sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaBootRpcProperties.java
sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaRpcAutoConfiguration.java
sofa-boot-project/sofa-boot-autoconfigure/src/test/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaRpcAutoConfigurationTests.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/container/ProviderConfigContainer.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/container/ProviderConfigDelayRegisterChecker.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/extension/ProviderConfigDelayRegisterChecker.java
sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/main/java/com/alipay/sofa/smoke/tests/rpc/boot/bean/delayregister/DelayRegisterService.java
sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/main/java/com/alipay/sofa/smoke/tests/rpc/boot/bean/delayregister/DelayRegisterServiceImpl.java
sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/main/resources/META-INF/sofa-rpc/rpc-config.json
sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/main/resources/spring/test_only_delay_register.xml
sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/test/java/com/alipay/sofa/smoke/tests/rpc/delayregister/DelayRegisterTests.java

在`rpc-sofa-boot`里定义一个否允许延迟服务发布至注册中心的扩展点，然后在`sofa-boot-actuator`里判断应用的健康状态，通过后再继续注册到注册中心。
demo地址：https://github.com/wangchengming666/sofa-boot-delay-demo
需要在配置里加上这两行
```
sofa.boot.rpc.enable-auto-publish=true
sofa.boot.rpc.enable-delay-register=true
```
我的demo验证情况如下，我有一个接口配置了延时10s发布、然后应用启动后会2s循环调用一下，理论上前4~5次都会出现`Cannot get the service address of service`的异常，之后会正常调用，控制台日志打印如下
```
2024-02-23 14:50:39.740  INFO 66775 --- [           main] .b.s.StartupSpringApplicationRunListener : Started SOFABoot Demo in 2.556 seconds
com.alipay.sofa.rpc.core.exception.SofaRouteException: RPC-020060001: Cannot get the service address of service [com.example.sofabootprovider.HelloService:1.0], please check the registry log. 
at com.alipay.sofa.rpc.client.AbstractCluster.noAvailableProviderException(AbstractClu …
```

fix #1276  after healthcheck double check success, register async

---

sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/PolarisRegistryConfiguration.java
sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/RegistryConfigurations.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/config/PolarisRegistryConfigurator.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/config/SofaBootRpcConfigConstants.java
sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/config/PolarisRegistryConfiguratorTests.java

Support PolarisRegistryConfiguration

Support PolarisRegistryConfiguration

---

sofa-boot-project/sofa-boot-core/rpc-sofa-boot/pom.xml
sofa-boot-project/sofaboot-dependencies/pom.xml

protoc 3.7.1 don't support osx-aarch_64
https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.7.1/
Minimum supported version is 3.17.3:
https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.17.3/
io.grpc:protoc-gen-grpc-java 1.28.0 don't support osx-aarch_64
https://repo.maven.apache.org/maven2/io/grpc/protoc-gen-grpc-java/1.28.0/
Minimum supported version is 1.42.3:
https://repo.maven.apache.org/maven2/io/grpc/protoc-gen-grpc-java/1.42.3/

Support mac M1(osx-aarch_64) compile and test

---

pom.xml
sofa-boot-tests/pom.xml

Reverts sofastack/sofa-boot#1382

Revert "Change OSSRH to Central Portal"
